services:
  python:
    build: .
    container_name: parcial1-ia-grupo6
    volumes:
    - ./src:/app/src
    - ./notebooks:/app/notebooks
    - ./data:/app/data
    working_dir: /app
    command: tail -f /dev/null